{% set name = "howardhinnant_date" %}
{% set version = "3.0.2" %}
{% set sha256 = "0449667ea85c5b411c28d08a53f1e420c73416caa5b693c249dac9763eb97b7c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/HowardHinnant/date/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0001-Locate-zoneinfo-based-on-install-prefix.patch

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('howardhinnant_date', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]
    - pkg-config
    - gnuconfig
  host:
    - dirent  # [win]
  run:
    - tzdata

test:
  requires:
    - cmake
    - {{ compiler('cxx') }}
    - ninja
  files:
    - test
  commands:
    - test -d ${PREFIX}/include/date  # [unix]
    - test -f ${PREFIX}/include/date/date.h  # [unix]
    - test -f ${PREFIX}/lib/libdate-tz${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/lib/cmake/date/dateConfig.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\date\date.h exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\bin\date-tz.dll exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\cmake\dateConfig.cmake exit 1  # [win]
    - cd test
    - cmake . -GNinja -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release
    - ln -s ${PREFIX}/share/zoneinfo/UTC ${PREFIX}/share/zoneinfo/CondaTest  # [unix]
    - mklink %PREFIX%\share\zoneinfo\CondaTest %PREFIX%\share\zoneinfo\UTC  # [win]
    - ./program  # [unix]
    - program.exe  # [win]

about:
  home: http://github.com/HowardHinnant/date
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A C++ date and time library
  description: A date and time library based on the C++11/14/17 <chrono> header
  doc_url: http://howardhinnant.github.io/date/date.html
  dev_url: http://github.com/HowardHinnant/date

extra:
  recipe-maintainers:
    - JohanMabille
    - jjerphan
    - pidefrem
    - gabm
    - apmorton
